### ISSUE TITLE
Questions about storable and background actions

### ISSUE THREAD

**Issue by rsoesemann** [ruslan-kurchenko/sfdc-lax#12]
Neighter from your (great) nor from Salesforce's documentation I understand:

1.  Why I can't use the setStorable caching when I use Promises. Even Lax doesn't allow me to use it besides in its action builder.
2. What the background option is and when I can use it? Can I use it whenever I don't need the response from the server?

**Comment by ruslan-kurchenko** [comment]
@rsoesemann 
1. _Why I can't use the setStorable caching when I use Promises?_
___Storable action flow:___
![210](https://user-images.githubusercontent.com/29373749/35811626-9b610888-0a97-11e8-910f-5ad8f6e04ab7.png)

From MDN about Promise https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#Description
_A **Promise** is a proxy for a value not necessarily known when the promise is created. It allows you to associate handlers with an asynchronous action's eventual success value or failure reason. This lets asynchronous methods return values like synchronous methods: instead of immediately returning the final value, the asynchronous method returns a promise to supply the value at some point in the future._

_A **Promise** is in one of these states:_
 - _`pending`: initial state, neither fulfilled nor rejected._
 - _`fulfilled`: meaning that the operation completed successfully._
 - _`rejected`: meaning that the operation failed._

The thing is that when a lightning server action callback called, the logic fulfills or reject a promise based on a result of the action (`SUCCESS` or `ERROR` for example). 
_When either of these options happens, the associated handlers queued up by a promise's `then` method are called._
**Note:** The Promise can be fulfilled or rejected and only once! See **[5]** step in the picture above - an action callback is called twice. In this case, it will try to `fulfill/reject` a promise again. But due to Promise behavior, it won't trigger callback again:
```javascript
new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve(10);
    resolve(20);
  }, 500);
})
.then(result => {
  console.log(result);
});
```
The above script will output to the console `10`. The second `resolve(20);` function call does nothing.

2. _What the background option is and when I can use it? Can I use it whenever I don't need the response from the server?_
As you might know, when you `enqueue` an action to the server, you don't run it. Basically, you tell the framework to put the action in the actions queue. At the end of the event loop, the framework sends HPXML request to the server with a batch of actions. So if framework sends 5 actions, the server waits for all Apex controller methods result from these actions and only then sends a batch response.
Well, when you mark an action as **background**, the framework does not place it in the queue along with **foreground** actions. Basically, it sends it separately. You may use it for long-running Apex controller logic. That will help you to avoid stunning(blocking) other queued actions.
Also, see Foreground and Background Actions docs:https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/controllers_server_background_actions.htm

**Comment by rsoesemann** [comment]
Your links actually brought me to a page with an explanation that nailed it for me:

> Storable actions might have their **callbacks invoked more than once**: first with cached data, then with updated data from the server. The **multiple invocations don't align well with promises,** which are expected to resolve or reject only once.

**Comment by ruslan-kurchenko** [comment]
I'm glad to hear that it helped you!
